/**
 * CyberSage - Security Rule Definitions
 *
 * Purpose:
 *   Configurable set of 25 passive security configuration rules.
 *   Each rule checks HTTP headers, cookies, and HTTPS config
 *   and returns a finding object if a misconfiguration is detected.
 *
 * Rule Structure:
 *   {
 *     id:             string   — Unique rule identifier
 *     name:           string   — Short rule name
 *     category:       string   — Grouping category
 *     severity:       string   — critical | high | medium | low | info
 *     description:    string   — What this rule checks
 *     risk:           string   — What could go wrong if missing
 *     recommendation: string   — How to fix it
 *     reference:      string   — MDN / OWASP / RFC link
 *     scoreImpact:    number   — Points deducted from score if triggered
 *     check:          Function — (scanData) => finding | null
 *   }
 *
 * check() receives:
 *   {
 *     headers:   object  — All HTTP response headers (lowercase keys)
 *     cookies:   array   — Parsed cookie objects
 *     httpsInfo: object  — { enabled, redirectsToHttps }
 *     serverInfo: object — { server, poweredBy, statusCode }
 *   }
 *
 * check() returns:
 *   null            — Rule passed (no finding)
 *   { evidence }    — Rule failed (finding generated by engine)
 */

const RULES = [

  // ════════════════════════════════════════
  // CATEGORY: HTTPS SECURITY
  // ════════════════════════════════════════

  {
    id:          'HTTPS-001',
    name:        'HTTPS Not Enabled',
    category:    'HTTPS Security',
    severity:    'critical',
    scoreImpact: 20,
    description: 'The website is served over HTTP without encryption.',
    risk:        'All data transmitted between users and the server is sent in plaintext. Attackers can intercept credentials, session tokens, and sensitive data using man-in-the-middle (MITM) attacks.',
    recommendation: 'Enable HTTPS on your web server and obtain a valid TLS certificate from a trusted CA (e.g., Let\'s Encrypt). Redirect all HTTP traffic to HTTPS.',
    reference:   'https://developer.mozilla.org/en-US/docs/Web/Security/Transport_Layer_Security',
    check: ({ httpsInfo }) => {
      if (!httpsInfo.enabled) {
        return { evidence: 'Site is served over HTTP (not HTTPS)' };
      }
      return null;
    }
  },

  {
    id:          'HTTPS-002',
    name:        'HTTP to HTTPS Redirect Missing',
    category:    'HTTPS Security',
    severity:    'high',
    scoreImpact: 10,
    description: 'The website does not redirect HTTP traffic to HTTPS.',
    risk:        'Users who visit the site via HTTP will not be automatically upgraded to a secure connection, exposing their data to interception.',
    recommendation: 'Configure your web server to permanently redirect (301) all HTTP requests to the HTTPS equivalent URL.',
    reference:   'https://cheatsheetseries.owasp.org/cheatsheets/Transport_Layer_Protection_Cheat_Sheet.html',
    check: ({ httpsInfo }) => {
      if (httpsInfo.enabled && !httpsInfo.redirectsToHttps) {
        return { evidence: 'HTTP version of the site does not redirect to HTTPS' };
      }
      return null;
    }
  },

  // ════════════════════════════════════════
  // CATEGORY: SECURITY HEADERS
  // ════════════════════════════════════════

  {
    id:          'HDR-001',
    name:        'Content-Security-Policy Missing',
    category:    'Security Headers',
    severity:    'high',
    scoreImpact: 15,
    description: 'The Content-Security-Policy (CSP) header is not present in the HTTP response.',
    risk:        'Without CSP, the browser has no instructions to restrict resource loading. This makes the site significantly more vulnerable to Cross-Site Scripting (XSS) and data injection attacks.',
    recommendation: 'Implement a strict Content-Security-Policy header. Start with: Content-Security-Policy: default-src \'self\'; script-src \'self\'; object-src \'none\';',
    reference:   'https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy',
    check: ({ headers }) => {
      if (!headers['content-security-policy']) {
        return { evidence: 'Header not present' };
      }
      return null;
    }
  },

  {
    id:          'HDR-002',
    name:        'Weak Content-Security-Policy (unsafe-inline)',
    category:    'Security Headers',
    severity:    'medium',
    scoreImpact: 8,
    description: 'The Content-Security-Policy header contains \'unsafe-inline\' which undermines XSS protection.',
    risk:        'Allowing unsafe-inline permits inline JavaScript execution, negating most of the XSS protection that CSP provides.',
    recommendation: 'Remove \'unsafe-inline\' from your CSP. Use nonces or hashes for legitimate inline scripts instead.',
    reference:   'https://content-security-policy.com/unsafe-inline/',
    check: ({ headers }) => {
      const csp = headers['content-security-policy'] || '';
      if (csp && csp.includes("'unsafe-inline'")) {
        return { evidence: `CSP contains 'unsafe-inline': ${csp.substring(0, 100)}` };
      }
      return null;
    }
  },

  {
    id:          'HDR-003',
    name:        'Weak Content-Security-Policy (unsafe-eval)',
    category:    'Security Headers',
    severity:    'medium',
    scoreImpact: 7,
    description: 'The Content-Security-Policy header contains \'unsafe-eval\' which allows dynamic code execution.',
    risk:        'Allowing unsafe-eval enables eval(), Function(), setTimeout(string) etc. which can be exploited by attackers to execute injected code.',
    recommendation: 'Remove \'unsafe-eval\' from your CSP. Refactor JavaScript to avoid eval() and similar constructs.',
    reference:   'https://content-security-policy.com/unsafe-eval/',
    check: ({ headers }) => {
      const csp = headers['content-security-policy'] || '';
      if (csp && csp.includes("'unsafe-eval'")) {
        return { evidence: `CSP contains 'unsafe-eval': ${csp.substring(0, 100)}` };
      }
      return null;
    }
  },

  {
    id:          'HDR-004',
    name:        'Strict-Transport-Security Missing',
    category:    'Security Headers',
    severity:    'high',
    scoreImpact: 12,
    description: 'The Strict-Transport-Security (HSTS) header is missing from the HTTPS response.',
    risk:        'Without HSTS, browsers may access the site over HTTP even if HTTPS is available. This enables SSL stripping attacks where MITM attackers downgrade HTTPS to HTTP.',
    recommendation: 'Add the HSTS header: Strict-Transport-Security: max-age=31536000; includeSubDomains; preload',
    reference:   'https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security',
    check: ({ headers, httpsInfo }) => {
      if (httpsInfo.enabled && !headers['strict-transport-security']) {
        return { evidence: 'HSTS header not present on HTTPS response' };
      }
      return null;
    }
  },

  {
    id:          'HDR-005',
    name:        'HSTS max-age Too Low',
    category:    'Security Headers',
    severity:    'low',
    scoreImpact: 4,
    description: 'The Strict-Transport-Security header has a max-age below the recommended minimum (1 year).',
    risk:        'A short HSTS max-age means browsers stop enforcing HTTPS quickly, reducing the protection window against SSL stripping attacks.',
    recommendation: 'Set max-age to at least 31536000 (1 year): Strict-Transport-Security: max-age=31536000; includeSubDomains',
    reference:   'https://hstspreload.org/',
    check: ({ headers }) => {
      const hsts = headers['strict-transport-security'];
      if (hsts) {
        const match = hsts.match(/max-age=(\d+)/i);
        if (match) {
          const maxAge = parseInt(match[1], 10);
          if (maxAge < 31536000) {
            return { evidence: `max-age=${maxAge} (recommended: 31536000)` };
          }
        }
      }
      return null;
    }
  },

  {
    id:          'HDR-006',
    name:        'X-Frame-Options Missing',
    category:    'Security Headers',
    severity:    'medium',
    scoreImpact: 8,
    description: 'The X-Frame-Options header is missing.',
    risk:        'Without X-Frame-Options, the page can be embedded in an iframe on any domain. This enables Clickjacking attacks where users are tricked into interacting with the site through a hidden iframe.',
    recommendation: 'Add: X-Frame-Options: DENY  or  X-Frame-Options: SAMEORIGIN. Alternatively, use CSP: frame-ancestors \'none\'.',
    reference:   'https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options',
    check: ({ headers }) => {
      const xfo = headers['x-frame-options'];
      const csp = headers['content-security-policy'] || '';
      const hasFrameAncestors = csp.includes('frame-ancestors');
      if (!xfo && !hasFrameAncestors) {
        return { evidence: 'X-Frame-Options header not present and no CSP frame-ancestors directive' };
      }
      return null;
    }
  },

  {
    id:          'HDR-007',
    name:        'X-Content-Type-Options Missing',
    category:    'Security Headers',
    severity:    'medium',
    scoreImpact: 6,
    description: 'The X-Content-Type-Options header is missing.',
    risk:        'Without this header, browsers may perform MIME-type sniffing and execute files as a different content type than declared. This can lead to XSS if a script is disguised as an image.',
    recommendation: 'Add: X-Content-Type-Options: nosniff',
    reference:   'https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options',
    check: ({ headers }) => {
      if (!headers['x-content-type-options']) {
        return { evidence: 'Header not present' };
      }
      return null;
    }
  },

  {
    id:          'HDR-008',
    name:        'Referrer-Policy Missing',
    category:    'Security Headers',
    severity:    'low',
    scoreImpact: 4,
    description: 'The Referrer-Policy header is not set.',
    risk:        'Without Referrer-Policy, the browser may send the full URL (including query parameters with sensitive data) in the Referer header to third-party websites.',
    recommendation: 'Add: Referrer-Policy: strict-origin-when-cross-origin  or  Referrer-Policy: no-referrer',
    reference:   'https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy',
    check: ({ headers }) => {
      if (!headers['referrer-policy']) {
        return { evidence: 'Header not present' };
      }
      return null;
    }
  },

  {
    id:          'HDR-009',
    name:        'Permissions-Policy Missing',
    category:    'Security Headers',
    severity:    'low',
    scoreImpact: 3,
    description: 'The Permissions-Policy header is not set.',
    risk:        'Without Permissions-Policy, the site does not restrict access to powerful browser features (camera, microphone, geolocation) for embedded content, increasing the risk of feature abuse.',
    recommendation: 'Add: Permissions-Policy: geolocation=(), microphone=(), camera=(), payment=()',
    reference:   'https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy',
    check: ({ headers }) => {
      if (!headers['permissions-policy'] && !headers['feature-policy']) {
        return { evidence: 'Header not present' };
      }
      return null;
    }
  },

  {
    id:          'HDR-010',
    name:        'Cross-Origin-Opener-Policy Missing',
    category:    'Security Headers',
    severity:    'low',
    scoreImpact: 3,
    description: 'The Cross-Origin-Opener-Policy (COOP) header is not set.',
    risk:        'Without COOP, cross-origin windows can gain access to your window object, enabling XS-Leaks and Spectre-based side-channel attacks.',
    recommendation: 'Add: Cross-Origin-Opener-Policy: same-origin',
    reference:   'https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy',
    check: ({ headers }) => {
      if (!headers['cross-origin-opener-policy']) {
        return { evidence: 'Header not present' };
      }
      return null;
    }
  },

  {
    id:          'HDR-011',
    name:        'Cross-Origin-Embedder-Policy Missing',
    category:    'Security Headers',
    severity:    'low',
    scoreImpact: 3,
    description: 'The Cross-Origin-Embedder-Policy (COEP) header is not set.',
    risk:        'Without COEP, the page cannot isolate itself from cross-origin resources, limiting access to certain high-resolution timers and SharedArrayBuffer used in Spectre mitigations.',
    recommendation: 'Add: Cross-Origin-Embedder-Policy: require-corp',
    reference:   'https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy',
    check: ({ headers }) => {
      if (!headers['cross-origin-embedder-policy']) {
        return { evidence: 'Header not present' };
      }
      return null;
    }
  },

  {
    id:          'HDR-012',
    name:        'Cross-Origin-Resource-Policy Missing',
    category:    'Security Headers',
    severity:    'low',
    scoreImpact: 3,
    description: 'The Cross-Origin-Resource-Policy (CORP) header is not set.',
    risk:        'Without CORP, resources can be loaded cross-origin, potentially enabling information leakage via speculative execution side channels.',
    recommendation: 'Add: Cross-Origin-Resource-Policy: same-origin',
    reference:   'https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Resource-Policy',
    check: ({ headers }) => {
      if (!headers['cross-origin-resource-policy']) {
        return { evidence: 'Header not present' };
      }
      return null;
    }
  },

  {
    id:          'HDR-013',
    name:        'Cache-Control Not Set',
    category:    'Security Headers',
    severity:    'low',
    scoreImpact: 4,
    description: 'The Cache-Control header is missing or does not restrict caching of sensitive responses.',
    risk:        'Sensitive pages without proper Cache-Control directives may be cached by browsers or intermediary proxies, exposing sensitive data to subsequent users of the same device or proxy.',
    recommendation: 'For pages with sensitive data add: Cache-Control: no-store, no-cache, must-revalidate, private',
    reference:   'https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control',
    check: ({ headers }) => {
      if (!headers['cache-control']) {
        return { evidence: 'Cache-Control header not present' };
      }
      return null;
    }
  },

  // ════════════════════════════════════════
  // CATEGORY: INFORMATION LEAKAGE
  // ════════════════════════════════════════

  {
    id:          'INFO-001',
    name:        'Server Header Exposes Technology',
    category:    'Information Leakage',
    severity:    'medium',
    scoreImpact: 5,
    description: 'The Server header reveals the web server software and version.',
    risk:        'Disclosing the server software and version number gives attackers a head start in identifying known vulnerabilities specific to that version.',
    recommendation: 'Configure your web server to suppress or anonymize the Server header. In Nginx: server_tokens off;  In Apache: ServerTokens Prod;',
    reference:   'https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/01-Information_Gathering/02-Fingerprint_Web_Server',
    check: ({ headers }) => {
      const server = headers['server'];
      if (server) {
        // Check if version numbers or technology names are exposed
        const revealsVersion = /[\d.]+/.test(server);
        const revealsTech    = /(apache|nginx|iis|tomcat|jetty|lighttpd|caddy|express)/i.test(server);
        if (revealsVersion || revealsTech) {
          return { evidence: `Server: ${server}` };
        }
      }
      return null;
    }
  },

  {
    id:          'INFO-002',
    name:        'X-Powered-By Header Exposes Technology',
    category:    'Information Leakage',
    severity:    'medium',
    scoreImpact: 5,
    description: 'The X-Powered-By header reveals the server-side technology stack.',
    risk:        'Revealing the backend technology (PHP, ASP.NET, Express, etc.) and version assists attackers in targeting known vulnerabilities for that platform.',
    recommendation: 'Remove the X-Powered-By header entirely. In Express.js: app.disable(\'x-powered-by\');  In PHP: expose_php = Off in php.ini',
    reference:   'https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/01-Information_Gathering/08-Fingerprint_Web_Application_Framework',
    check: ({ headers }) => {
      if (headers['x-powered-by']) {
        return { evidence: `X-Powered-By: ${headers['x-powered-by']}` };
      }
      return null;
    }
  },

  {
    id:          'INFO-003',
    name:        'Deprecated X-XSS-Protection Header Present',
    category:    'Information Leakage',
    severity:    'info',
    scoreImpact: 2,
    description: 'The deprecated X-XSS-Protection header is set.',
    risk:        'X-XSS-Protection is obsolete and has been removed from modern browsers. Relying on it for XSS protection is ineffective. The "1; mode=block" value can actually create new vulnerabilities in some browsers.',
    recommendation: 'Remove X-XSS-Protection and implement a proper Content-Security-Policy instead.',
    reference:   'https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection',
    check: ({ headers }) => {
      if (headers['x-xss-protection']) {
        return { evidence: `X-XSS-Protection: ${headers['x-xss-protection']} (deprecated header)` };
      }
      return null;
    }
  },

  // ════════════════════════════════════════
  // CATEGORY: COOKIE SECURITY
  // ════════════════════════════════════════

  {
    id:          'COOK-001',
    name:        'Cookie Missing Secure Flag',
    category:    'Cookie Security',
    severity:    'high',
    scoreImpact: 10,
    description: 'One or more cookies are set without the Secure flag.',
    risk:        'Cookies without the Secure flag can be transmitted over unencrypted HTTP connections. If a user accesses the site via HTTP (or if an attacker downgrades the connection), these cookies can be stolen.',
    recommendation: 'Add the Secure flag to all cookies: Set-Cookie: session=abc; Secure; HttpOnly; SameSite=Strict',
    reference:   'https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#security',
    check: ({ cookies }) => {
      const insecure = cookies.filter(c => !c.secure);
      if (insecure.length > 0) {
        const names = insecure.map(c => c.name).join(', ');
        return { evidence: `Cookies without Secure flag: ${names}` };
      }
      return null;
    }
  },

  {
    id:          'COOK-002',
    name:        'Cookie Missing HttpOnly Flag',
    category:    'Cookie Security',
    severity:    'high',
    scoreImpact: 10,
    description: 'One or more cookies are set without the HttpOnly flag.',
    risk:        'Cookies without HttpOnly are accessible via JavaScript (document.cookie). If XSS is present, an attacker can steal session cookies and hijack user accounts.',
    recommendation: 'Add the HttpOnly flag to all session/authentication cookies: Set-Cookie: session=abc; Secure; HttpOnly; SameSite=Strict',
    reference:   'https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#restrict_access_to_cookies',
    check: ({ cookies }) => {
      const noHttpOnly = cookies.filter(c => !c.httpOnly);
      if (noHttpOnly.length > 0) {
        const names = noHttpOnly.map(c => c.name).join(', ');
        return { evidence: `Cookies without HttpOnly flag: ${names}` };
      }
      return null;
    }
  },

  {
    id:          'COOK-003',
    name:        'Cookie Missing SameSite Attribute',
    category:    'Cookie Security',
    severity:    'medium',
    scoreImpact: 6,
    description: 'One or more cookies are set without the SameSite attribute.',
    risk:        'Without SameSite, cookies are sent with cross-site requests, enabling Cross-Site Request Forgery (CSRF) attacks where malicious sites perform actions on behalf of authenticated users.',
    recommendation: 'Add SameSite=Strict or SameSite=Lax to all cookies: Set-Cookie: session=abc; Secure; HttpOnly; SameSite=Strict',
    reference:   'https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#samesitesamesite-value',
    check: ({ cookies }) => {
      const noSameSite = cookies.filter(c => !c.sameSite);
      if (noSameSite.length > 0) {
        const names = noSameSite.map(c => c.name).join(', ');
        return { evidence: `Cookies without SameSite attribute: ${names}` };
      }
      return null;
    }
  },

  // ════════════════════════════════════════
  // CATEGORY: CORS / ORIGIN POLICY
  // ════════════════════════════════════════

  {
    id:          'CORS-001',
    name:        'Wildcard Access-Control-Allow-Origin',
    category:    'CORS Security',
    severity:    'medium',
    scoreImpact: 7,
    description: 'The Access-Control-Allow-Origin header is set to wildcard (*) which allows any origin.',
    risk:        'A wildcard CORS policy allows any website to make cross-origin requests and read the response. This can expose sensitive data in API responses to malicious sites.',
    recommendation: 'Restrict CORS to specific trusted origins: Access-Control-Allow-Origin: https://yourdomain.com',
    reference:   'https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS',
    check: ({ headers }) => {
      const acao = headers['access-control-allow-origin'];
      if (acao === '*') {
        return { evidence: 'Access-Control-Allow-Origin: * (wildcard — any origin allowed)' };
      }
      return null;
    }
  },

  // ════════════════════════════════════════
  // CATEGORY: INFO (Informational)
  // ════════════════════════════════════════

  {
    id:          'INFO-004',
    name:        'HTTPS Enabled',
    category:    'HTTPS Security',
    severity:    'info',
    scoreImpact: 0,
    description: 'The site is served over HTTPS.',
    risk:        'N/A — This is a positive finding.',
    recommendation: 'Maintain your HTTPS configuration and ensure certificates are renewed before expiry.',
    reference:   'https://developer.mozilla.org/en-US/docs/Web/Security/Transport_Layer_Security',
    check: ({ httpsInfo }) => {
      // This is a POSITIVE check — return finding only when HTTPS IS enabled (informational)
      if (httpsInfo.enabled) {
        return { evidence: 'Site is served over HTTPS', positive: true };
      }
      return null;
    }
  },

  {
    id:          'INFO-005',
    name:        'No Cookies Detected',
    category:    'Cookie Security',
    severity:    'info',
    scoreImpact: 0,
    description: 'No Set-Cookie headers were detected in the response.',
    risk:        'N/A — Informational only.',
    recommendation: 'Ensure any cookies set later in the session have appropriate Secure, HttpOnly, and SameSite attributes.',
    reference:   'https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies',
    check: ({ cookies }) => {
      if (cookies.length === 0) {
        return { evidence: 'No cookies set in this response', positive: true };
      }
      return null;
    }
  }

];

module.exports = RULES;
